# Generated by Django 6.1.1 on 2026-09-10 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Platform Super Admin'), ('OWNER', 'Organization Owner'), ('HR_ADMIN', 'HR / Admin'), ('MANAGER', 'Department Manager'), ('EMPLOYEE', 'Employee / Staff')], db_index=True, default='EMPLOYEE', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Primary organization for this user upon login')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this membership is currently enabled')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Membership',
                'verbose_name_plural': 'Organization Memberships',
                'ordering': ['-is_default', 'organization__name'],
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
