# Generated by Django 6.1.1 on 2026-09-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Computer Science, Human Resources, Cardiology', max_length=150)),
                ('code', models.CharField(help_text='Short code unique within the organization, e.g. CSE, HR, CARD', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Mission or scope of the department')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['organization', 'name'],
            },
        ),
    ]
