# Generated by Django 6.1.1 on 2026-09-10 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('employees', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Head of department or manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(help_text='Tenant organization that owns this department', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organizations.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('organization', 'code')},
        ),
    ]
