# Generated by Django 6.1.1 on 2026-09-10 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_name', models.CharField(help_text='e.g. Master Degree Certificate, Passport Copy', max_length=200)),
                ('document_type', models.CharField(choices=[('RESUME', 'Resume / CV'), ('ID_PROOF', 'Government ID Proof'), ('QUALIFICATION', 'Degree / Certificate'), ('EXPERIENCE', 'Experience Certificate'), ('JOINING_LETTER', 'Appointment / Joining Letter'), ('OTHER', 'Other Document')], db_index=True, default='OTHER', max_length=30)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Size in bytes')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('expiry_date', models.DateField(blank=True, help_text='Optional expiry date for IDs or licenses', null=True)),
                ('notes', models.TextField(blank=True, help_text='Verification remarks or notes')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Document',
                'verbose_name_plural': 'Employee Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
