# Generated by Django 6.1.1 on 2026-09-10 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('ARCHIVE', 'Archived'), ('RESTORE', 'Restored'), ('DELETE', 'Deleted'), ('LOGIN', 'User Logged In'), ('LOGOUT', 'User Logged Out'), ('DOCUMENT_UPLOAD', 'Document Uploaded'), ('DOCUMENT_VERIFY', 'Document Verified'), ('ROLE_ASSIGN', 'Role Assigned')], db_index=True, max_length=50)),
                ('entity_type', models.CharField(db_index=True, help_text='e.g. Employee, Department, Organization', max_length=100)),
                ('entity_id', models.CharField(blank=True, help_text='Primary key or identifier of the entity', max_length=100)),
                ('description', models.TextField(help_text='Detailed audit message')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
