# Generated by Django 6.1.1 on 2026-09-10 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('employee_id', models.CharField(db_index=True, help_text='Organization-specific Employee/Staff ID (e.g. EMP-101, FAC-204, DR-501)', max_length=50)),
                ('full_name', models.CharField(db_index=True, max_length=200)),
                ('date_of_birth', models.DateField(help_text='Date of birth')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], default='PREFER_NOT_TO_SAY', max_length=20)),
                ('email', models.EmailField(db_index=True, help_text='Work or personal email address', max_length=254)),
                ('phone_number', models.CharField(help_text='Contact telephone/mobile number', max_length=30)),
                ('address', models.TextField(help_text='Permanent or residential address')),
                ('designation', models.CharField(db_index=True, help_text='e.g. Senior Software Engineer, Assistant Professor, Staff Nurse', max_length=150)),
                ('qualification', models.CharField(help_text='Highest qualification (e.g. M.Tech in CSE, Ph.D, MBBS, MD, MBA)', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Professional summary or biography')),
                ('joining_date', models.DateField(db_index=True, help_text='Date the employee joined the organization')),
                ('employment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('RESIGNED', 'Resigned'), ('RETIRED', 'Retired'), ('TERMINATED', 'Terminated'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=20)),
                ('profile_photo', models.ImageField(blank=True, help_text='Passport-style photo or avatar', null=True, upload_to='employee_photos/')),
                ('department', models.ForeignKey(help_text='Department within the organization', on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='departments.department')),
                ('organization', models.ForeignKey(help_text='Tenant organization', on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organizations.organization')),
                ('user', models.OneToOneField(blank=True, help_text='Optional login user account for employee self-service portal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['organization', 'full_name'],
                'indexes': [models.Index(fields=['organization', 'employment_status'], name='employees_e_organiz_144578_idx'), models.Index(fields=['organization', 'department'], name='employees_e_organiz_f61392_idx')],
                'unique_together': {('organization', 'employee_id')},
            },
        ),
    ]
