# Generated by Django 6.1.1 on 2026-09-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Unique name of the organization', max_length=255, unique=True)),
                ('organization_type', models.CharField(choices=[('COLLEGE', 'College'), ('UNIVERSITY', 'University'), ('SCHOOL', 'School'), ('COMPANY', 'Company'), ('HOSPITAL', 'Hospital'), ('GOVERNMENT', 'Government Organization'), ('PRIVATE', 'Private Organization'), ('NGO', 'Non-Governmental Organization (NGO)'), ('OTHER', 'Other')], db_index=True, default='COMPANY', help_text='Classification of the organization', max_length=30)),
                ('email', models.EmailField(help_text='Official contact email', max_length=254)),
                ('phone', models.CharField(help_text='Primary phone number', max_length=30)),
                ('address', models.TextField(help_text='Physical or postal address')),
                ('website', models.URLField(blank=True, help_text='Official website', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Brief background or overview')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_logos/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
    ]
